---
title: "Project 1 Dataset Creation"
author: "Rachel Austin"
date: "2026-02-25"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/austinra/BIOS6624/Project 1")
library(dplyr)
library(tidyr)
library(Hmisc)
library(gtsummary)
library(gt)
```


```{r}
df <- read.csv("Data Raw/hiv_6624_final.csv")
#Filter dataset to visit years of interest
df <- filter(df, years == 0  |years == 2)
#Grab only columns we're interested in for this analysis:
df <- select(df, newid, years, VLOAD, LEU3N, AGG_MENT, AGG_PHYS, hard_drugs, ADH, age, BMI, RACE, EDUCBAS, SMOKE )
```


```{r}
#Determine paired outcomes 
paired_all4 <- df %>%    
  group_by(newid) %>%
  summarise(
    has_both_visits = n_distinct(years) == 2,
    all4_paired = has_both_visits &&
      all(!is.na(VLOAD)) &&
      all(!is.na(LEU3N)) &&
      all(!is.na(AGG_MENT)) &&
      all(!is.na(AGG_PHYS)),
    .groups = "drop"
  )

#Dataframe of just these subjects
df_all4 <- df %>%
  semi_join(filter(paired_all4, all4_paired), by = "newid")

```


Collapsing factor variables
```{r}
#Collapse education
#0 is no college degree, 1 is college degree and higher
df_all4 <- df_all4 %>%
  mutate(education = case_when(
    EDUCBAS %in% c(1,2,3,4) ~ 0,
    EDUCBAS %in% c(5,6,7) ~ 1,
    TRUE ~ NA_real_
  ),
  education = factor(
    education,
    levels = c(0, 1),
    labels = c("No college degree", "College degree or higher")))

#Collapse race
# 0 is White, non-Hispanic and 1 is other
df_all4 <- df_all4 %>%
  mutate(race = case_when(
    RACE  == 1 ~ 0,
    RACE %in% c(2,3,4,5,6,7,8) ~1,
    TRUE ~ NA_real_
  ),
  race = factor(
    race, 
    levels = c(0,1),
    labels = c("White, non-Hispanic", "Other")
  ))

#Collapse adherence to 95% adherence and above, then below 95%

df_all4 <- df_all4 %>% 
  mutate(adh = case_when(
    ADH == 1 ~ 0,
    ADH == 2 ~ 0,
    ADH == 3 ~ 1,
    ADH == 4 ~ 1,
    TRUE ~ NA_real_
  ),
  adh = factor(adh,
               levels = c(0,1),
               labels = c("95% or above", "Below 95%"))
  )


#Change invalid BMI values to missing
df_all4 <- df_all4 %>% mutate(bmi = case_when(
  BMI == -1 ~ NA,
  BMI == 999 ~ NA,
  BMI > 500 ~ NA,
  TRUE ~ BMI
))


#Convert years and smoke to factors, transform variables
df_all4 <- df_all4 %>%
  mutate(hard_drugs = factor(hard_drugs, levels = c(0,1), labels = c("No", "Yes")),
                             years = factor(years, levels = c(0,2)),
         SMOKE = factor(SMOKE, levels = c(1,2,3), labels = c("Never smoked", "Former smoker", "Current smoker")),
         log_vload = log(VLOAD))

```

Subset dataset down to baseline (year 0) covariates and then year 0 and year 2 values both displayed for outcomes
```{r}
#Baseline dataset
df_base <- df_all4 %>%
  filter(years == 0) %>%
  select(newid, hard_drugs, age, BMI, SMOKE, education, race)

# Year 2 adherence
df_adh2 <- df_all4 %>%
  filter(years == 2) %>%
  select(newid, adh) %>%
  rename(adh_2 = adh)

# Wide outcomes
df_wide <- df_all4 %>%
  select(newid, years, VLOAD, LEU3N, AGG_PHYS, AGG_MENT, log_vload) %>%
  pivot_wider(
    names_from = years,
    values_from = c(VLOAD, LEU3N, AGG_PHYS, AGG_MENT, log_vload),
    names_glue = "{.value}_{years}"
  )

# Merge everything
df_analysis <- df_base %>%
  left_join(df_adh2, by = "newid") %>%
  left_join(df_wide, by = "newid")

# Write dataset to folder for analysis
#openxlsx::write.xlsx(df_analysis, "Data Processed/Analysis Dataset.xlsx")

```


Table One Creation

```{r}

#Add labels
label(df_analysis$VLOAD_0)    <- "Viral Load at Baseline"
label(df_analysis$VLOAD_2)    <- "Viral Load at Year 2"
label(df_analysis$LEU3N_0)    <- "Number of CD4 Positive Cells at Baseline"
label(df_analysis$LEU3N_2)    <- "Number of CD4 Positive Cells at Year 2"
label(df_analysis$AGG_PHYS_0)   <- "Aggregate Physical Quality of Life Score at Baseline"
label(df_analysis$AGG_PHYS_2)   <- "Aggregate Physical Quality of Life Score at Year 2"
label(df_analysis$AGG_MENT_0)   <- "Aggregate Mental Quality of Life Score at Baseline"
label(df_analysis$AGG_MENT_2)   <- "Aggregate Mental Quality of Life Score at Year 2"
label(df_analysis$hard_drugs) <- "Hard Drug Use at Baseline"
label(df_analysis$adh_2)        <- "Adherence to Medicine at Year 2"
label(df_analysis$age)        <- "Age at Baseline"
label(df_analysis$BMI)        <- "Body Mass Index (kg/m^2)"
label(df_analysis$SMOKE)      <- "Smoking Status"
label(df_analysis$education)  <- "Education Level"
label(df_analysis$race)       <- "Race"



tbl <- df_analysis %>%
  select(
    VLOAD_0, VLOAD_2, LEU3N_0, LEU3N_2,
    AGG_PHYS_0, AGG_PHYS_2, AGG_MENT_0, AGG_MENT_2,
    adh_2, age, BMI, SMOKE, education, race, hard_drugs
  ) %>%
  tbl_summary(
    by = hard_drugs,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    digits = all_continuous() ~ 1,
    missing = "ifany",
    missing_text = "Missing"
  ) %>%
  add_overall(last = TRUE) %>%          
  modify_header(label ~ "**Characteristic**") %>%
  bold_labels() %>%
  modify_caption("**Table 1. Baseline characteristics by hard drug use**") %>%
  as_gt()

tbl
```

