---
title: "Primary Analysis"
author: "Rachel Austin"
date: "2026-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(gtsummary)
library(tidyr)
library(openxlsx)
library(survminer)
library(survival)
```

```{r}
df <- read.xlsx("/Users/austinra/BIOS6624/Project 3/Data Processed/survival_df.xlsx")

#Change to factor
df$SEX <- factor(df$SEX)
df$DIABETES <- factor(df$DIABETES)
df$BPMEDS <- factor(df$BPMEDS)
df$CURSMOKE <- factor(df$CURSMOKE)
df$PREVCHD <- factor(df$PREVCHD)

#Remove missing baseline values - below list is var with NA values in table one
df <- df %>% filter(complete.cases(BPMEDS, TOTCHOL, BMI))
```

Preliminary Visualizations
```{r}
surv <- survfit(Surv(TIME_STROKE, STROKE)~SEX, data = df)
ggsurvplot(surv, censor = F)
ggsurvplot(surv, censor = F, fun= "cloglog")
```

Separate male and female data for analysis
```{r}
male_df <- filter(df, SEX ==1)
female_df <- filter(df, SEX ==2)
```

Stratified KM - Age
```{r}
surv_male <- Surv(time = male_df$TIME_STROKE, event = male_df$STROKE)

quantile(male_df$AGE, probs = c(0, 0.33, 0.66, 1), na.rm = TRUE)

male_df$age_group <- cut(
  male_df$AGE,
  breaks = quantile(male_df$AGE, probs = c(0, 0.33, 0.66, 1)),
  include.lowest = TRUE,
  labels = c("33-44", "45-54", "55-69")
)

km_male_age <- survfit(surv_male ~ age_group, data = male_df)
ggsurvplot(km_male_age, 
           data = male_df, 
           risk.table = TRUE,
           ylim = c(0.90, 1.00),   
           legend.title = "Age",
           legend.labs = c("33-44", "45-54", "55-69"),
           xlab = "Time (days)",
           ylab = "Cumulative stroke incidence")

```
Stratified KM - SYSBP
```{r}
male_df$sysbp_group <- ifelse(male_df$SYSBP < 160, "<160", "≥160")
male_df$sysbp_group <- factor(male_df$sysbp_group, levels = c("<160", "≥160"))


km_sysbp <- survfit(surv_male ~ sysbp_group, data = male_df)

ggsurvplot(
  km_sysbp,
  data = male_df,           
  ylim = c(0.8, 1.0),   
  risk.table = TRUE,
  legend.title = "Systolic BP",
  legend.labs = c("<160 mmHg", "≥160 mmHg"),
  xlab = "Time (days)",
  ylab = "Cumulative stroke incidence"
)
```
Stratified KM - Diabetes
```{r}
km_diab <- survfit(surv_male ~ DIABETES, data = male_df)

ggsurvplot(
  km_diab,
  data = male_df,           
  ylim = c(0.7, 1.0),   
  risk.table = TRUE,
  legend.title = "Diabetes",
  legend.labs = c("No", "Yes"),
  xlab = "Time (days)",
  ylab = "Cumulative stroke incidence"
)
```

Manual backwards selection
```{r}
full_male_mod <- coxph(Surv(TIME_STROKE, STROKE) ~ AGE + DIABETES  + SYSBP + PREVCHD + BPMEDS + CURSMOKE + TOTCHOL + BMI, 
                    data = male_df)
summary(full_male_mod)
```


```{r}
reduced_male_mod1 <- update(full_male_mod, . ~ . - PREVCHD)
summary(reduced_male_mod1)

reduced_male_mod2 <- update(reduced_male_mod1, . ~ . - BMI)
summary(reduced_male_mod2)

reduced_male_mod3 <- update(reduced_male_mod2, . ~  . - TOTCHOL)
summary(reduced_male_mod3)

reduced_male_mod <- reduced_male_mod3
summary(reduced_male_mod)
```

Schoenfield Residuals
```{r}
male_ph_check <- cox.zph(reduced_male_mod)
male_ph_check
```


```{r}
male_high_bp <- 160
male_normal_bp <- mean(male_df$SYSBP, na.rm = TRUE)

# Base profiles (non-smokers)
male_newdata <- expand.grid(
  AGE = c(40, 50, 60),
  DIABETES = c(0, 1),
  SYSBP = c(male_normal_bp, male_high_bp)
)

male_newdata$CURSMOKE <- 0

# Add smoker version ONLY for baseline (no diabetes + normal BP)
baseline_smoker <- male_newdata %>%
  filter(DIABETES == 0, SYSBP == male_normal_bp) %>%
  mutate(CURSMOKE = 1)

# Combine
male_newdata <- rbind(male_newdata, baseline_smoker)

# Match factor structure
male_newdata$DIABETES <- factor(
  male_newdata$DIABETES,
  levels = levels(male_df$DIABETES)
)

male_newdata$CURSMOKE <- factor(
  male_newdata$CURSMOKE,
  levels = levels(male_df$CURSMOKE)
)

male_newdata$BPMEDS <- 0

# Labels (no pipes)
male_newdata$profile <- with(male_newdata, paste0(
  "Age ", AGE, ", ",
  ifelse(DIABETES == 1, "Diabetes", "No Diabetes"), ", ",
  ifelse(SYSBP == male_high_bp, "High BP", "Normal BP"),
  ifelse(CURSMOKE == 1, ", Smoker", "")
))

# Fit survival
male_prob_fit <- survfit(reduced_male_mod, newdata = male_newdata)

male_prob_fit_10 <- summary(male_prob_fit, times = 365.25*10)

male_results <- data.frame(
  profile = male_newdata$profile,
  survival_10yr = as.vector(male_prob_fit_10$surv)
)

male_table <- male_results %>%
  mutate(
    survival_pct = round(survival_10yr * 100, 1),
    risk_pct = round((1 - survival_10yr) * 100, 1)
  ) %>%
  mutate(
    survival_10yr = paste0(survival_pct, "%"),
    risk_10yr = paste0(risk_pct, "%")
  ) %>%
  select(profile, survival_10yr, risk_10yr) %>%
  rename(
    Profile = profile,
    `10-Year Survival` = survival_10yr,
    `10-Year Stroke Risk` = risk_10yr
  )
 

kable(
  male_table,
  align = c("l", "c", "c"),
  caption = "Predicted 10-Year Survival and Stroke Risk for Male Risk Profiles"
) %>%
  kable_styling(full_width = FALSE, position = "left")

```























Stratified KM - Age
```{r}
surv_female <- Surv(time = female_df$TIME_STROKE, event = female_df$STROKE)

quantile(female_df$AGE, probs = c(0, 0.33, 0.66, 1), na.rm = TRUE)

female_df$age_group <- cut(
  female_df$AGE,
  breaks = quantile(female_df$AGE, probs = c(0, 0.33, 0.66, 1)),
  include.lowest = TRUE,
  labels = c("32-45", "46-54", "55-70")
)

km_female_age <- survfit(surv_female ~ age_group, data = female_df)
ggsurvplot(km_female_age, 
           data = female_df, 
           risk.table = TRUE,
           ylim = c(0.90, 1.00),   
           legend.title = "Age Range",
           legend.labs = c("32-45", "46-54", "55-70"),
           xlab = "Time (days)",
           ylab = "Cumulative stroke incidence")
```

Stratified KM - SYSBP
```{r}
female_df$sysbp_group <- ifelse(female_df$SYSBP < 160, "<160", "≥160")
female_df$sysbp_group <- factor(female_df$sysbp_group, levels = c("<160", "≥160"))


km_sysbp <- survfit(surv_female ~ sysbp_group, data = female_df)

ggsurvplot(
  km_sysbp,
  data = female_df,           
  ylim = c(0.8, 1.0),   
  risk.table = TRUE,
  legend.title = "Systolic BP",
  legend.labs = c("<160 mmHg", "≥160 mmHg"),
  xlab = "Time (days)",
  ylab = "Cumulative stroke incidence"
)
```

Stratified KM - Diabetes
```{r}
km_diab <- survfit(surv_female ~ DIABETES, data = female_df)

ggsurvplot(
  km_diab,
  data = female_df,           
  ylim = c(0.8, 1.0),   
  risk.table = TRUE,
  legend.title = "Diabetes",
  legend.labs = c("No", "Yes"),
  xlab = "Time (days)",
  ylab = "Cumulative stroke incidence"
)
```


```{r}
full_female_mod <- coxph(Surv(TIME_STROKE, STROKE) ~ AGE + DIABETES  + SYSBP + PREVCHD + BPMEDS + CURSMOKE + TOTCHOL + BMI, 
                    data = female_df)

summary(full_female_mod)
```

Manual Backwards Selection
```{r}
reduced_female_mod1 <- update(full_female_mod, . ~ . - BMI)
summary(reduced_female_mod1)

reduced_female_mod2 <- update(reduced_female_mod1, . ~ . - TOTCHOL)
summary(reduced_female_mod2)

reduced_female_mod3 <- update(reduced_female_mod2, . ~  . - BPMEDS)
summary(reduced_female_mod3)

reduced_female_mod4 <- update(reduced_female_mod3, . ~ . -PREVCHD)
summary(reduced_female_mod4)

reduced_female_mod <- update(reduced_female_mod4, . ~  . -CURSMOKE)
summary(reduced_female_mod)
```

Schoenfield Residuals
```{r}
female_ph_check <- cox.zph(reduced_female_mod)
female_ph_check
```


```{r}
female_mean_chol <- mean(female_df$TOTCHOL, na.rm = TRUE)
female_mean_bmi  <- mean(female_df$BMI, na.rm = TRUE)

# Define normal and high SYSBP
female_normal_bp <- mean(female_df$SYSBP, na.rm = TRUE)
female_high_bp <- 160

female_newdata <- expand.grid(
  AGE = c(40, 50, 60),
  DIABETES = c(0, 1),
  SYSBP = c(female_normal_bp, female_high_bp)
)

female_newdata$profile <- with(female_newdata, paste0(
  "Age ", AGE, ", ",
  ifelse(DIABETES == 1, "Diabetes", "No Diabetes"), ", ",
  ifelse(SYSBP == female_high_bp, "High BP", "Normal BP")
))

female_prob_fit <- survfit(reduced_female_mod, newdata = female_newdata)

female_prob_fit_10 <- summary(female_prob_fit, times = 365.25*10)

female_results <- data.frame(
  profile = female_newdata$profile,
  AGE = female_newdata$AGE,
  survival_10yr = as.vector(female_prob_fit_10$surv)
)

female_results$risk_10yr <- 1 - female_results$survival_10yr

female_table <- female_results %>%
  mutate(
    survival_10yr = paste0(round(survival_10yr * 100, 1), "%"),
    risk_10yr = paste0(round(risk_10yr * 100, 1), "%")
  ) %>%
  select(profile, survival_10yr, risk_10yr) %>%
  rename(
    Profile = profile,
    `10-Year Survival` = survival_10yr,
    `10-Year Stroke Risk` = risk_10yr
  )

kable(
  female_table,
  align = c("l", "c", "c"),
  caption = "Predicted 10-Year Survival and Stroke Risk for Female Risk Profiles"
) %>%
  kable_styling(full_width = FALSE, position = "left")
```

Combined Hazard Ratio Table for Report
```{r}

tbl_male <- tbl_regression(
  reduced_male_mod,
  exponentiate = TRUE,
  show_single_row = c(DIABETES, CURSMOKE, BPMEDS),
  label = list(
    AGE ~ "Age (per year)",
    DIABETES ~ "Diabetes",
    SYSBP ~ "Systolic Blood Pressure (per mmHg)",
    CURSMOKE ~ "Current Smoker",
    BPMEDS ~ "Blood Pressure Medication Use"
  )
) %>%
  modify_fmt_fun(
    estimate ~ function(x) style_number(x, digits = 2),
    conf.low ~ function(x) style_number(x, digits = 2),
    conf.high ~ function(x) style_number(x, digits = 2),
    p.value ~ function(x) style_pvalue(x, digits = 2)
  ) %>%
  modify_column_merge(
    pattern = "{estimate} ({conf.low}, {conf.high})",
    rows = !is.na(estimate)
  ) %>%
  modify_column_hide(c(conf.low, conf.high)) %>%
  modify_header(
    label = "**Variable**",
    estimate = "**Hazard Ratio (95% CI)**",
    p.value = "**p-value**"
  ) %>% 
  modify_caption("**Hazard Ratios for 10-Year Stroke Risk (Males)**")

tbl_male

tbl_female <- tbl_regression(
  reduced_female_mod,
  exponentiate = TRUE,
  show_single_row = c(DIABETES),
  label = list(
    AGE ~ "Age (per year)",
    DIABETES ~ "Diabetes",
    SYSBP ~ "Systolic Blood Pressure (per mmHg)"
  )
) %>%
  modify_fmt_fun(
    estimate ~ function(x) style_number(x, digits = 2),
    conf.low ~ function(x) style_number(x, digits = 2),
    conf.high ~ function(x) style_number(x, digits = 2),
    p.value ~ function(x) style_pvalue(x, digits = 2)
  ) %>%
  modify_column_merge(
    pattern = "{estimate} ({conf.low}, {conf.high})",
    rows = !is.na(estimate)
  ) %>%
  modify_column_hide(c(conf.low, conf.high)) %>%
  modify_header(
    label = "**Variable**",
    estimate = "**Hazard Ratio (95% CI)**",
    p.value = "**p-value**"
  )%>% 
  modify_caption("**Hazard Ratios for 10-Year Stroke Risk (Females)**")

tbl_female

# 
# tbl_combined <- tbl_merge(
#   tbls = list(tbl_male, tbl_female),
#   tab_spanner = c("**Males**", "**Females**")
# ) %>%
#   bold_labels()
# 
# tbl_combined
```

